### ISSUE TITLE
create meta.xml files for event core and occurrence core

### ISSUE THREAD

**Issue by mobb** [EDIorg/ecocomDP#87]
To generate GBIF submissions from ecocomDP, we will include a meta.xml file describing the tables and columns. We plan to create two types: occurrence core, and event core.

First pass will be column names. 

Still to resolve/confirm:

- [ ] line endings (depend on the system generating the file)
- [ ] rowType names the core-type 
- [ ] location (filename - are these all the same? or vary with pkg?)
- [ ] indexing: is it true that files are zero-based, but fields are 1-based?

**Comment by clnsmth** [comment]
Line endings are explicitly defined as **\r\n**

**Comment by clnsmth** [comment]
@mobb location file name doesn't vary with pkg (I've checked this off the list). What do we need to do about rowType and indexing? Are these items resolved?

**Comment by tucotuco** [comment]
Hello. I am the convener of the Darwin Core Maintenance Group and have recently read https://doi.org/10.1016/j.ecoinf.2021.101374 and I am concerned about some misconceptions put forth there. I wonder if there is anything I can help with in terms of the best use of Darwin Core and aggregation via GBIF.

**Comment by mobb** [comment]
Absolutely, @tucotuco - it would be great to have additional input, especially if we are misinterpreting DC. We are still working on this last bit of code. Here is an example of what it currently creates: https://portal.edirepository.org/nis/mapbrowse?packageid=edi.927.1
I am out of the office till later in August - perhaps we can talk then?

**Comment by tucotuco** [comment]
Great! I look forward to sharing perspectives as we try to flex Darwin Core
Archives out of the star schema restriction. Let me know by email when you
are ready for a discussion, and thanks!
